[[inputs.mqtt_consumer]]

  servers = ["tcp://127.0.0.1:1883"] # 127.0.0.1 is the localhost ip and 1883 is the default port for mqtt

  topics = [
    "satellite/telemetry"
  ]

  data_format = "json"

  [[outputs.influxdb_v2]]

  urls = ["http://127.0.0.1:8086"]

  token = "YOUR_INFLUX_TOKEN"

  organization = "personal"

  bucket = "satelliteTelemetry"